services:
  - type: web
    name: ids2025-streamlit
    env: python
    plan: free

    buildCommand: pip install -r requirements.txt

    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0

    envVars:
      - key: PYTHON_VERSION
        value: 3.13.14
